import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="w-full flex items-center px-6 py-4 bg-white shadow-sm z-50">
          <a href="/" className="flex items-center gap-3">
            <Image src="/logo.png" alt="CheckMyPartner Logo" width={48} height={48} className="rounded-lg" priority />
            <span className="font-bold text-xl text-gray-900 tracking-tight">checkyourpartner.com</span>
          </a>
        </header>
        {children}
      </body>
    </html>
  );
}
