import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";
import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <Head>
        <meta property="og:title" content="CheckYourPartner.com – Loyalty Test Service" />
        <meta property="og:description" content="Test your partner's loyalty with our confidential, AI-powered service. Get proof, peace of mind, and results in 5 days." />
        <meta property="og:image" content="/logo2.jpeg" />
        <meta property="og:url" content="https://checkyourpartner.com" />
        <meta property="og:type" content="website" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="CheckYourPartner.com – Loyalty Test Service" />
        <meta name="twitter:description" content="Test your partner's loyalty with our confidential, AI-powered service. Get proof, peace of mind, and results in 5 days." />
        <meta name="twitter:image" content="/logo2.jpeg" />
      </Head>
      <body className="font-sans bg-gray-50 text-gray-900 min-h-screen flex flex-col relative overflow-hidden">
        <header className="w-full flex items-center px-6 py-4 bg-white shadow-sm z-50">
          <Link href="/" className="flex items-center gap-3">
            <Image src="/logo.png" alt="CheckMyPartner Logo" width={48} height={48} className="rounded-lg" priority />
            <span className="font-bold text-xl text-gray-900 tracking-tight">checkyourpartner.com</span>
          </Link>
        </header>
        {children}
      </body>
    </html>
  );
}
